os: linux

dist: xenial

language: cpp

compiler:
  - g++-7
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - g++-7-multilib
    env:
      - COMPILER="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${COMPILER}"

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
