matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
      env:
        - COMPILER="CC=gcc-7 && CXX=g++-7"
    before_install:
      - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 500
  - os: linux
    language: cpp
    compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
  - os: windows
    language: cpp
    compiler: clang
  - os: osx
    language: cpp
    compiler: clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
    cmake --build .
  - cmake --build . --target test
