language: cpp

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test


matrix:
  include:
  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - g++-7-multilib
      env:
        - COMPILER="CC=gcc-7 && CXX=g++-7"
    before_install:
      - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 500
  - os: windows
  - os: osx